name: leetcode_dart
description: Some solved problems from https://leetcode.com on Dart
version: 1.0.5
homepage: https://github.com/fartem/leetcode-dart

environment:
  sdk: '>=3.6.9 <4.0.0'

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
