name: leetcode_dart
description: Some solved problems from https://leetcode.com on Dart
version: 1.0.0
homepage: https://github.com/fartem/leetcode-dart

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
