name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DART_VERSION: "3.7.2"

jobs:
  analyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart analyze

  formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart format -l 120 --set-exit-if-changed ./

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test -c source
